[window]
decorations = "buttonless"
opacity = 0.769
startup_mode = "Maximized"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 21

[colors.primary]
background = '#030712'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black = '#020617'
red = '#ef4444'
green = '#065f46'
yellow = '#fde68a'
blue = '#083344'
magenta = '#581c87'
cyan = '#f2f4f8'
white = '#dfdfe0'

# Bright colors
[colors.bright]
black = '#9ca3af'
red = '#f16da6'
green = '#46c880'
yellow = '#2dc7c4'
blue = '#8cb6ff'
magenta = '#c8a5ff'
cyan = '#52bdff'
white = '#e4e4e5'
