import = [ "~/.config/alacritty/themes/themes/kanagawa_dragon.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 0.95
startup_mode = "Maximized"

[font]
size = 21

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

# import:
#   - ~/.config/alacritty/themes/themes/kanagawa_dragon.toml
# env:
#   TERM: xterm-256color
# window:
#   decorations: buttonless
#   opacity: 0.95
#   startup_mode: Maximized
# font:
#   normal:
#     family: Hack Nerd Font
#     style: Regular
#   size: 21
# key_bindings:
#   - { key: J,        mods: Alt,     chars: "\x1bj"                       }
#   - { key: K,        mods: Alt,     chars: "\x1bk"                       }
#   - { key: H,        mods: Alt,     chars: "\x1bh"                       }
#   - { key: L,        mods: Alt,     chars: "\x1bl"                       }
